### ISSUE TITLE
Use kuboRpcModule instead of ipfsHttpModule in ipfs/interop

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-kubo-rpc-client#4]
Originally from https://github.com/ipfs/kubo/issues/9125

> switch https://github.com/ipfs/interop to talk to Kubo daemon over js-kubo-rpc-client and run it in the CI of js-kubo-rpc-client repo(we already run ipfs/interop tests in Kubo CI, but it is too late, we should do it in the library repo CI too)

- [x] ipfs/interop/issues/487
- [x] update ipfs/interop to latest ipfsd-ctl - see https://github.com/ipfs/interop/pull/493
- [x] update ipfs/interop to latest ipfs-http-client
- [ ] Ensure ipfs/interop uses kubo-rpc-client when talking to kubo

**Comment by SgtPooki** [comment]
Opened issue for ipfs/interop not working by default for M1 Macs, https://github.com/ipfs/interop/issues/487
Opened PR with fix and improved error message: https://github.com/ipfs/interop/pull/488

**Comment by SgtPooki** [comment]
`npm run test` is running after updating ipfs/interop to use kuboRpcClient, but there are some failures:

```bash
╭─    ~/code/work/protocol.ai/ipfs/interop    feature/add-js-kubo-rpc-client !3 ?2 ───── ▼  2.30.3 ▼  16.12.0   15:11:39  ─╮
╰─ ✘ 1 ❯ npm run test

> ipfs-interop@8.0.0 pretest
> aegir build --esm-tests

[15:12:18] Clean ./dist [started]
[15:12:18] Clean ./dist [completed]
[15:12:18] Build ESM [started]
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/src/index.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/src/index.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/browser.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/cid-version-agnostic.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/exchange-files.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/files.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/ipns-pubsub.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/ipns.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/kad-dht.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/node.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pin.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pubsub.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v1/all.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v2/all.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v1/browser.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v2/browser.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/circuit.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/relayd.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/daemon-factory.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/wait-for.js
parsing file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/pin-utils.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v2/browser.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/relayd.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/wait-for.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/daemon-factory.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/files.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/ipns-pubsub.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/ipns.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/cid-version-agnostic.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/kad-dht.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pubsub.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/exchange-files.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/pin-utils.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pin.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/utils/circuit.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v1/all.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v2/all.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit/v1/browser.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/circuit.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/browser.js
parsed file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/node.js
'nanoid' is imported by dist/esm/browser-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/browser-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'uint8arrays/from-string' is imported by dist/esm/browser-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/node-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/node-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'uint8arrays/from-string' is imported by dist/esm/node-test/cid-version-agnostic.js, but could not be resolved – treating it as an external dependency
'detect-node' is imported by dist/esm/browser-test/circuit.js, but could not be resolved – treating it as an external dependency
'detect-node' is imported by dist/esm/node-test/circuit.js, but could not be resolved – treating it as an external dependency
'iso-random-stream/src/random.js' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'pretty-bytes' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'random-fs' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'util' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'rimraf' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'is-ci' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'is-os' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'os' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'ipfs-utils/src/files/glob-source.js' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/browser-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'iso-random-stream/src/random.js' is imported by dist/esm/browser-test/files.js, but could not be resolved – treating it as an external dependency
'ipfs-unixfs' is imported by dist/esm/browser-test/files.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/browser-test/files.js, but could not be resolved – treating it as an external dependency
'it-all' is imported by dist/esm/browser-test/files.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/browser-test/files.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/files.js, but could not be resolved – treating it as an external dependency
'iso-random-stream/src/random.js' is imported by dist/esm/node-test/files.js, but could not be resolved – treating it as an external dependency
'ipfs-unixfs' is imported by dist/esm/node-test/files.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/node-test/files.js, but could not be resolved – treating it as an external dependency
'it-all' is imported by dist/esm/node-test/files.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/node-test/files.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/files.js, but could not be resolved – treating it as an external dependency
'peer-id' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'multiformats/bases/base58' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'ipns' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'p-retry' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'uint8arrays/to-string' is imported by dist/esm/browser-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'iso-random-stream/src/random.js' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'pretty-bytes' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'random-fs' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'util' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'rimraf' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'is-ci' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'is-os' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'os' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'ipfs-utils/src/files/glob-source.js' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/node-test/exchange-files.js, but could not be resolved – treating it as an external dependency
'os' is imported by dist/esm/browser-test/ipns.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/browser-test/ipns.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/browser-test/ipns.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/browser-test/ipns.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/browser-test/ipns.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/ipns.js, but could not be resolved – treating it as an external dependency
'peer-id' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'multiformats/bases/base58' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'ipns' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'p-retry' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'uint8arrays/to-string' is imported by dist/esm/node-test/ipns-pubsub.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/browser-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'p-defer' is imported by dist/esm/browser-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'uint8arrays' is imported by dist/esm/browser-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'wherearewe' is imported by dist/esm/browser-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'it-to-buffer' is imported by dist/esm/browser-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'os' is imported by dist/esm/node-test/ipns.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/node-test/ipns.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/node-test/ipns.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/node-test/ipns.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/node-test/ipns.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/ipns.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/node-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'p-defer' is imported by dist/esm/node-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'uint8arrays' is imported by dist/esm/node-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'wherearewe' is imported by dist/esm/node-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'it-to-buffer' is imported by dist/esm/node-test/kad-dht.js, but could not be resolved – treating it as an external dependency
'fs' is imported by dist/esm/browser-test/pin.js, but could not be resolved – treating it as an external dependency
'it-all' is imported by dist/esm/browser-test/pin.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/browser-test/pin.js, but could not be resolved – treating it as an external dependency
'it-drain' is imported by dist/esm/browser-test/pin.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/pin.js, but could not be resolved – treating it as an external dependency
'fs' is imported by dist/esm/node-test/pin.js, but could not be resolved – treating it as an external dependency
'it-all' is imported by dist/esm/node-test/pin.js, but could not be resolved – treating it as an external dependency
'it-last' is imported by dist/esm/node-test/pin.js, but could not be resolved – treating it as an external dependency
'it-drain' is imported by dist/esm/node-test/pin.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/pin.js, but could not be resolved – treating it as an external dependency
'p-retry' is imported by dist/esm/browser-test/pubsub.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/pubsub.js, but could not be resolved – treating it as an external dependency
'uint8arrays/from-string' is imported by dist/esm/browser-test/pubsub.js, but could not be resolved – treating it as an external dependency
'uint8arrays/equals' is imported by dist/esm/browser-test/pubsub.js, but could not be resolved – treating it as an external dependency
'p-retry' is imported by dist/esm/node-test/pubsub.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/pubsub.js, but could not be resolved – treating it as an external dependency
'uint8arrays/from-string' is imported by dist/esm/node-test/pubsub.js, but could not be resolved – treating it as an external dependency
'uint8arrays/equals' is imported by dist/esm/node-test/pubsub.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/node-test/circuit/v1/browser.js, but could not be resolved – treating it as an external dependency
'wherearewe' is imported by dist/esm/node-test/circuit/v1/browser.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'iso-random-stream/src/random.js' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'libp2p-websockets' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'p-retry' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'libp2p-websockets/src/filters.js' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/node-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'detect-node' is imported by dist/esm/browser-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'fs' is imported by dist/esm/browser-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/browser-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'execa' is imported by dist/esm/browser-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'go-platform' is imported by dist/esm/browser-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'iso-random-stream/src/random.js' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'it-concat' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'libp2p-websockets' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'p-retry' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'libp2p-websockets/src/filters.js' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'aegir/utils/chai.js' is imported by dist/esm/browser-test/utils/circuit.js, but could not be resolved – treating it as an external dependency
'ipfsd-ctl' is imported by dist/esm/browser-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'detect-node' is imported by dist/esm/browser-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'kubo-rpc-client' is imported by dist/esm/browser-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'ipfs' is imported by dist/esm/browser-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'ipfsd-ctl' is imported by dist/esm/node-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'detect-node' is imported by dist/esm/node-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'kubo-rpc-client' is imported by dist/esm/node-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'ipfs' is imported by dist/esm/node-test/utils/daemon-factory.js, but could not be resolved – treating it as an external dependency
'detect-node' is imported by dist/esm/node-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'fs' is imported by dist/esm/node-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/node-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'execa' is imported by dist/esm/node-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'go-platform' is imported by dist/esm/node-test/utils/relayd.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/browser-test/utils/wait-for.js, but could not be resolved – treating it as an external dependency
'os' is imported by dist/esm/browser-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/browser-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/browser-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'it-all' is imported by dist/esm/browser-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'it-drain' is imported by dist/esm/browser-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'os' is imported by dist/esm/node-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'path' is imported by dist/esm/node-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'nanoid' is imported by dist/esm/node-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'it-all' is imported by dist/esm/node-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'it-drain' is imported by dist/esm/node-test/utils/pin-utils.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/node-test/utils/wait-for.js, but could not be resolved – treating it as an external dependency
'delay' is imported by dist/esm/browser-test/circuit/v1/browser.js, but could not be resolved – treating it as an external dependency
'wherearewe' is imported by dist/esm/browser-test/circuit/v1/browser.js, but could not be resolved – treating it as an external dependency
[15:12:18] Build ESM [completed]
[15:12:18] Bundle [started]
[15:12:18] Bundle [completed]
[15:12:18] Generate types [started]
[15:12:18] Generate types [completed]

> ipfs-interop@8.0.0 test
> cross-env LIBP2P_TCP_REUSEPORT=false aegir test

Test Node.js
Warning: Cannot find any files matching pattern "test/**/*.spec.{js,ts,cjs,mjs}"


  ipns-pubsub
    ✔ should get enabled state of pubsub
    1) should publish the received record to a go node and a js subscriber should receive it
    2) should publish the received record to a js node and a go subscriber should receive it

  CID version agnostic
    ✔ should add v0 and cat v1 (go0 -> go0) (223ms)
    ✔ should add v0 and cat v1 (js0 -> js0) (81ms)
    ✔ should add v0 and cat v1 (go0 -> go1) (288ms)
    ✔ should add v0 and cat v1 (js0 -> js1) (111ms)
    ✔ should add v0 and cat v1 (js0 -> go0) (100ms)
    ✔ should add v0 and cat v1 (go0 -> js0) (326ms)
    ✔ should add v1 and cat v0 (go0 -> go0) (206ms)
    ✔ should add v1 and cat v0 (js0 -> js0) (83ms)
    ✔ should add v1 and cat v0 (go0 -> go1) (290ms)
    ✔ should add v1 and cat v0 (js0 -> js1) (98ms)
    ✔ should add v1 and cat v0 (js0 -> go0) (77ms)
    ✔ should add v1 and cat v0 (go0 -> js0) (288ms)

  pubsub
    publish from Go, subscribe on Go
      3) "before all" hook: connect for "should exchange ascii data"
    publish from JS, subscribe on JS
      4) "before all" hook: connect for "should exchange ascii data"
    publish from JS, subscribe on Go
      5) "before all" hook: connect for "should exchange ascii data"
    publish from Go, subscribe on JS
      6) "before all" hook: connect for "should exchange ascii data"

  circuit
    v1
      go-rv1-go
        ✔ connect (1015ms)
        ✔ send (311ms)
      js-rv1-js
        ✔ connect (1091ms)
        ✔ send (79ms)
      js-rv1-go
        ✔ connect (1056ms)
        ✔ send (112ms)
      go-rv1-js
        ✔ connect (1060ms)
        ✔ send (260ms)
      go-js-go
        ✔ connect (1061ms)
        ✔ send (291ms)
      js-js-go
        ✔ connect (1096ms)
        ✔ send (130ms)
      go-js-js
        ✔ connect (1095ms)
        ✔ send (255ms)
      js-js-js
        ✔ connect (1123ms)
        ✔ send (79ms)
    v2
      go-rv2-go
        ✔ connect (1014ms)
      js-rv2-js
        - connect
      js-rv2-go
        - connect
      go-rv2-js
        - connect
      go-go-go
        ✔ connect (1012ms)
      js-go-go
        - connect
      go-go-js
        - connect
      js-go-js
        - connect
      go-js-go
        - connect
      js-js-go
        - connect
      go-js-js
        - connect
      js-js-js
        - connect

  exchange files
    go -> js
      7) "before all" hook: connect in "go -> js"
    go -> go2
      8) "before all" hook: connect in "go -> go2"
    js -> go
      9) "before all" hook: connect in "js -> go"
    js -> js2
      10) "before all" hook: connect in "js -> js2"

  ipns locally using the same repo across implementations
    ✔ should publish an ipns record to a js daemon and resolve it using the same js daemon (4487ms)
    ✔ should publish an ipns record to a go daemon and resolve it using the same go daemon (4336ms)
    - should publish an ipns record to a js daemon and resolve it using a go daemon through the reuse of the same repo
    - should publish an ipns record to a go daemon and resolve it using a js daemon through the reuse of the same repo

  kad-dht
    kad-dht with a bootstrap node
      a JS network
        ✔ should get from the network after being added (136ms)
      a GO network
        ✔ should get from the network after being added (577ms)
      a JS bootstrap node in the land of Go
        ✔ should get from the network after being added (509ms)
      a Go bootstrap node in the land of JS
        ✔ should get from the network after being added (129ms)
      a JS bootstrap node in a hybrid land
        ✔ should get from the network after being added (298ms)
      a Go bootstrap node in a hybrid land
        ✔ should get from the network after being added (128ms)
    kad-dht with multiple hops
      a JS node in the land of Go
        ✔ one hop (483ms)
        ✔ two hops (328ms)
        ✔ three hops (348ms)
      a Go node in the land of JS
        ✔ one hop (83ms)
        ✔ two hops (131ms)
        ✔ three hops (103ms)
      a hybrid network, cat from GO
        ✔ one hop (108ms)
        ✔ two hops (318ms)
        ✔ three hops (114ms)
      a hybrid network, cat from JS
        ✔ one hop (291ms)
        ✔ two hops (389ms)
        ✔ three hops (116ms)
    kad-dht across disjoint networks that become joint
      a GO network
        ✔ join network (5612ms)
      a JS network
        ✔ join network (5195ms)
      a hybrid network, cat from GO
        ✔ join network (5588ms)
      a hybrid network, cat from JS
        ✔ join network (5201ms)

  pin
    pin add
      ✔ pin recursively
      ✔ pin directly
    pin rm
      ✔ pin recursively, remove the root pin
      ✔ remove a child shared by multiple pins
    ls
      ✔ print same pins

  files
    ✔ returns an error when reading non-existent files
    ✔ returns an error when writing deeply nested files and the parents do not exist
    - uses raw nodes for leaf data
    ✔ errors when creating the same directory twice (85ms)
    ✔ does not error when creating the same directory twice and parents option is passed (100ms)
    ✔ errors when creating the root directory
    has the same hashes for
      ✔ empty files (216ms)
      ✔ small files (288ms)
      ✔ big files (1105ms)
      ✔ files that have had data appended (401ms)
      ✔ files that have had data overwritten (406ms)
      ✔ small files with CIDv1 (267ms)
      ✔ big files with CIDv1 (1013ms)
      ✔ trickle DAGs (821ms)
      ✔ rabin chunker (517ms)
      ✔ rabin chunker small chunks (692ms)
      ✔ hamt shards (21952ms)
      ✔ updating mfs hamt shards (23164ms)


  77 passing (7m)
  13 pending
  10 failing

  1) ipns-pubsub
       should publish the received record to a go node and a js subscriber should receive it:
     Error: Could not find peer subscribing
      at file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/ipns-pubsub.js:127:11
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at RetryOperation._fn (node_modules/p-retry/index.js:50:12)

  2) ipns-pubsub
       should publish the received record to a js node and a go subscriber should receive it:
     Error: Could not find peer subscribing
      at file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/ipns-pubsub.js:127:11
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at RetryOperation._fn (node_modules/p-retry/index.js:50:12)

  3) pubsub
       publish from Go, subscribe on Go
         "before all" hook: connect for "should exchange ascii data":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWHDdTxQjv9zqTnVkizPfaNtcRos41rYvkb1XHQqSB1p2o){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pubsub.js:69:59)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  4) pubsub
       publish from JS, subscribe on JS
         "before all" hook: connect for "should exchange ascii data":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWF1gvZxzvRE9HPntnJ9MXZ97AaesQcoFK8BXes1vTMvJP){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pubsub.js:69:59)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  5) pubsub
       publish from JS, subscribe on Go
         "before all" hook: connect for "should exchange ascii data":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWGHhsggeLXyP6rdudHBbuH6ejgUGxa9i4ixtgc9UTrTCe){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pubsub.js:69:59)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  6) pubsub
       publish from Go, subscribe on JS
         "before all" hook: connect for "should exchange ascii data":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWHivjPfyjUtw13ZMJKQiiHfU6NW1j5LnGkrbphKX3F2zK){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/pubsub.js:69:59)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  7) exchange files
       go -> js
         "before all" hook: connect in "go -> js":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWCHNTLSx6CgKfMtrPjq5kW25Kf4u631M4ouinS6dQixtV){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/exchange-files.js:130:56)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  8) exchange files
       go -> go2
         "before all" hook: connect in "go -> go2":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWSJjaVzKxoArp2wFEp4Y2zf8pHzLgKZCXJeaGobSJ3Mhm){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/exchange-files.js:130:56)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  9) exchange files
       js -> go
         "before all" hook: connect in "js -> go":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWEsdtn78V4FDM8nC6B7p5nj1bU8VxMbcXp2fNQvtEvkaq){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/exchange-files.js:130:56)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  10) exchange files
       js -> js2
         "before all" hook: connect in "js -> js2":
     AssertionError: expected [ Array(1) ] to include PeerId(12D3KooWAc48rgf6zNf7VdZrPBiEZAGycn2K6Cf1Kb2LLURrfTkZ){ …(5) }
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/interop/test/exchange-files.js:130:56)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)



Command failed with exit code 10: mocha test/node.{js,ts,cjs,mjs} test/**/*.spec.{js,ts,cjs,mjs} --ui bdd --require source-map-support/register --timeout=60000
```
