### ISSUE TITLE
bug: ipfs refs is broken after kubo 12

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-kubo-rpc-client#77]
discovered during https://github.com/ipfs/js-kubo-rpc-client/issues/56

```bash
GO_IPFS_GAMUT=true npm run test -- -f 'test/interface-tests.spec.js' --bail=false -g 'should print added files'

> kubo-rpc-client@1.0.2 test
> aegir test "-f" "test/interface-tests.spec.js" "--bail=false" "-g" "should print added files"

test node.js

  go-ipfs current at undefined
    .refs
      1) should print added files

  go-ipfs 12.0 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-12.0/go-ipfs/ipfs
    .refs
      ✔ should print added files

  go-ipfs 12 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-12/go-ipfs/ipfs
    .refs
      ✔ should print added files

  go-ipfs 13 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-13/go-ipfs/ipfs
    .refs
      2) should print added files

  go-ipfs 14 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-14/go-ipfs/ipfs
    .refs
      3) should print added files

  go-ipfs 15 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-15/go-ipfs/ipfs
    .refs
      4) should print added files

  go-ipfs 16 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-16/go-ipfs/ipfs
    .refs
      5) should print added files


  2 passing (28s)
  5 failing

  1) go-ipfs current at undefined
       .refs
         should print added files:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) go-ipfs 13 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-13/go-ipfs/ipfs
       .refs
         should print added files:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  3) go-ipfs 14 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-14/go-ipfs/ipfs
       .refs
         should print added files:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  4) go-ipfs 15 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-15/go-ipfs/ipfs
       .refs
         should print added files:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  5) go-ipfs 16 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-16/go-ipfs/ipfs
       .refs
         should print added files:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SgtPooki** [comment]
```bash
> GO_IPFS_GAMUT=true npm run test -- -f 'test/interface-tests.spec.js' --bail=false -g 'should print files in edges format'

> kubo-rpc-client@1.0.2 test
> aegir test "-f" "test/interface-tests.spec.js" "--bail=false" "-g" "should print files in edges format"

test node.js


  go-ipfs current at undefined
    .refs
      1) should print files in edges format

  go-ipfs 12.0 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-12.0/go-ipfs/ipfs
    .refs
      ✔ should print files in edges format

  go-ipfs 12 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-12/go-ipfs/ipfs
    .refs
      ✔ should print files in edges format

  go-ipfs 13 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-13/go-ipfs/ipfs
    .refs
      2) should print files in edges format

  go-ipfs 14 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-14/go-ipfs/ipfs
    .refs
      3) should print files in edges format

  go-ipfs 15 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-15/go-ipfs/ipfs
    .refs
      4) should print files in edges format

  go-ipfs 16 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-16/go-ipfs/ipfs
    .refs
      5) should print files in edges format


  2 passing (28s)
  5 failing

  1) go-ipfs current at undefined
       .refs
         should print files in edges format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) go-ipfs 13 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-13/go-ipfs/ipfs
       .refs
         should print files in edges format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  3) go-ipfs 14 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-14/go-ipfs/ipfs
       .refs
         should print files in edges format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  4) go-ipfs 15 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-15/go-ipfs/ipfs
       .refs
         should print files in edges format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  5) go-ipfs 16 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-16/go-ipfs/ipfs
       .refs
         should print files in edges format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s -> QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SgtPooki** [comment]
```bash
GO_IPFS_GAMUT=true npm run test -- -f 'test/interface-tests.spec.js' --bail=false -g 'should print files in custom format'

> kubo-rpc-client@1.0.2 test
> aegir test "-f" "test/interface-tests.spec.js" "--bail=false" "-g" "should print files in custom format"

test node.js


  go-ipfs current at undefined
    .refs
      1) should print files in custom format

  go-ipfs 12.0 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-12.0/go-ipfs/ipfs
    .refs
      ✔ should print files in custom format

  go-ipfs 12 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-12/go-ipfs/ipfs
    .refs
      ✔ should print files in custom format

  go-ipfs 13 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-13/go-ipfs/ipfs
    .refs
      2) should print files in custom format

  go-ipfs 14 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-14/go-ipfs/ipfs
    .refs
      3) should print files in custom format

  go-ipfs 15 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-15/go-ipfs/ipfs
    .refs
      4) should print files in custom format

  go-ipfs 16 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-16/go-ipfs/ipfs
    .refs
      5) should print files in custom format


  2 passing (29s)
  5 failing

  1) go-ipfs current at undefined
       .refs
         should print files in custom format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "atlantic-animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "fruits: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +  "mushroom.txt: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) go-ipfs 13 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-13/go-ipfs/ipfs
       .refs
         should print files in custom format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "atlantic-animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "fruits: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +  "mushroom.txt: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  3) go-ipfs 14 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-14/go-ipfs/ipfs
       .refs
         should print files in custom format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "atlantic-animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "fruits: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +  "mushroom.txt: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  4) go-ipfs 15 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-15/go-ipfs/ipfs
       .refs
         should print files in custom format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "atlantic-animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "fruits: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +  "mushroom.txt: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  5) go-ipfs 16 at /Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/node_modules/go-ipfs-16/go-ipfs/ipfs
       .refs
         should print files in custom format:

      AssertionError: expected [] to deeply equal [ …(4) ]
      + expected - actual

      -[]
      +[
      +  "animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYEJ7qQNZUvBnv4SZ3rEbksagaan3sGvnUq948vSG8Z34"
      +  "atlantic-animals: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmUXzZKa3xhTauLektUiK4GiogHskuz1c57CnnoP4TgYJD"
      +  "fruits: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmYLvZrFn8KE2bcJ9UFhthScBVbbcXEgkJnnCBeKWYkpuQ"
      +  "mushroom.txt: Qmd5MhNjx3NSZm3L2QKG1TFvqkTRbtZwGJinqEfqpfHH7s => QmRfqT4uTUgFXhWbfBZm6eZxi2FQ8pqYK5tcWRyTZ7RcgY"
      +]

      at Context.<anonymous> (file:///Users/sgtpooki/code/work/protocol.ai/ipfs/js-kubo-rpc-client/test/interface-tests/src/refs.js:73:48)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SgtPooki** [comment]
note that GO_IPFS_GAMUT is no longer supported
